/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 64
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 65
#define ALIAS_COUNT 0
#define TOKEN_COUNT 43
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 7
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 12
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LF = 1,
  anon_sym_COMMA = 2,
  anon_sym_AT = 3,
  anon_sym_AMP = 4,
  anon_sym_fun = 5,
  sym_function_close = 6,
  anon_sym_return = 7,
  anon_sym_if = 8,
  anon_sym_EQ = 9,
  anon_sym_BANG_EQ = 10,
  anon_sym_LT = 11,
  anon_sym_GT = 12,
  anon_sym_LT_EQ = 13,
  anon_sym_GT_EQ = 14,
  anon_sym_while = 15,
  sym_end_block = 16,
  anon_sym_PLUS_EQ = 17,
  anon_sym_DASH_EQ = 18,
  anon_sym_STAR_EQ = 19,
  anon_sym_SLASH_EQ = 20,
  anon_sym_PERCENT_EQ = 21,
  anon_sym_PLUS = 22,
  anon_sym_DASH = 23,
  anon_sym_STAR = 24,
  anon_sym_SLASH = 25,
  anon_sym_PERCENT = 26,
  anon_sym_COLON = 27,
  anon_sym_LT_DASH = 28,
  anon_sym_sizeof = 29,
  anon_sym_free = 30,
  anon_sym_cat = 31,
  anon_sym_const = 32,
  anon_sym_string = 33,
  sym_identifier = 34,
  sym_value = 35,
  sym_string = 36,
  anon_sym_int = 37,
  anon_sym_float = 38,
  anon_sym_byte = 39,
  anon_sym_iarray = 40,
  anon_sym_farray = 41,
  sym_comment = 42,
  sym_source_file = 43,
  sym_line = 44,
  sym_statement = 45,
  sym_variable_definition = 46,
  sym_function_definition = 47,
  sym_function_return = 48,
  sym_if_statement = 49,
  sym_while_statement = 50,
  sym_unary_assignment = 51,
  sym_binary_assignment = 52,
  sym_set_array = 53,
  sym_get_array = 54,
  sym_array_size = 55,
  sym_clear_array = 56,
  sym_cat = 57,
  sym_parameter = 58,
  sym_ref_parameter = 59,
  sym_val_parameter = 60,
  sym_type = 61,
  aux_sym_source_file_repeat1 = 62,
  aux_sym_line_repeat1 = 63,
  aux_sym_function_definition_repeat1 = 64,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LF] = "\n",
  [anon_sym_COMMA] = ",",
  [anon_sym_AT] = "@",
  [anon_sym_AMP] = "&",
  [anon_sym_fun] = "fun",
  [sym_function_close] = "function_close",
  [anon_sym_return] = "return",
  [anon_sym_if] = "if",
  [anon_sym_EQ] = "=",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_while] = "while",
  [sym_end_block] = "end_block",
  [anon_sym_PLUS_EQ] = "+=",
  [anon_sym_DASH_EQ] = "-=",
  [anon_sym_STAR_EQ] = "*=",
  [anon_sym_SLASH_EQ] = "/=",
  [anon_sym_PERCENT_EQ] = "%=",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_PERCENT] = "%",
  [anon_sym_COLON] = ":",
  [anon_sym_LT_DASH] = "<-",
  [anon_sym_sizeof] = "sizeof",
  [anon_sym_free] = "free",
  [anon_sym_cat] = "cat",
  [anon_sym_const] = "const",
  [anon_sym_string] = "string",
  [sym_identifier] = "identifier",
  [sym_value] = "value",
  [sym_string] = "string",
  [anon_sym_int] = "int",
  [anon_sym_float] = "float",
  [anon_sym_byte] = "byte",
  [anon_sym_iarray] = "iarray",
  [anon_sym_farray] = "farray",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym_line] = "line",
  [sym_statement] = "statement",
  [sym_variable_definition] = "variable_definition",
  [sym_function_definition] = "function_definition",
  [sym_function_return] = "function_return",
  [sym_if_statement] = "if_statement",
  [sym_while_statement] = "while_statement",
  [sym_unary_assignment] = "unary_assignment",
  [sym_binary_assignment] = "binary_assignment",
  [sym_set_array] = "set_array",
  [sym_get_array] = "get_array",
  [sym_array_size] = "array_size",
  [sym_clear_array] = "clear_array",
  [sym_cat] = "cat",
  [sym_parameter] = "parameter",
  [sym_ref_parameter] = "ref_parameter",
  [sym_val_parameter] = "val_parameter",
  [sym_type] = "type",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_line_repeat1] = "line_repeat1",
  [aux_sym_function_definition_repeat1] = "function_definition_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_AT] = anon_sym_AT,
  [anon_sym_AMP] = anon_sym_AMP,
  [anon_sym_fun] = anon_sym_fun,
  [sym_function_close] = sym_function_close,
  [anon_sym_return] = anon_sym_return,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_while] = anon_sym_while,
  [sym_end_block] = sym_end_block,
  [anon_sym_PLUS_EQ] = anon_sym_PLUS_EQ,
  [anon_sym_DASH_EQ] = anon_sym_DASH_EQ,
  [anon_sym_STAR_EQ] = anon_sym_STAR_EQ,
  [anon_sym_SLASH_EQ] = anon_sym_SLASH_EQ,
  [anon_sym_PERCENT_EQ] = anon_sym_PERCENT_EQ,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_LT_DASH] = anon_sym_LT_DASH,
  [anon_sym_sizeof] = anon_sym_sizeof,
  [anon_sym_free] = anon_sym_free,
  [anon_sym_cat] = anon_sym_cat,
  [anon_sym_const] = anon_sym_const,
  [anon_sym_string] = anon_sym_string,
  [sym_identifier] = sym_identifier,
  [sym_value] = sym_value,
  [sym_string] = sym_string,
  [anon_sym_int] = anon_sym_int,
  [anon_sym_float] = anon_sym_float,
  [anon_sym_byte] = anon_sym_byte,
  [anon_sym_iarray] = anon_sym_iarray,
  [anon_sym_farray] = anon_sym_farray,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym_line] = sym_line,
  [sym_statement] = sym_statement,
  [sym_variable_definition] = sym_variable_definition,
  [sym_function_definition] = sym_function_definition,
  [sym_function_return] = sym_function_return,
  [sym_if_statement] = sym_if_statement,
  [sym_while_statement] = sym_while_statement,
  [sym_unary_assignment] = sym_unary_assignment,
  [sym_binary_assignment] = sym_binary_assignment,
  [sym_set_array] = sym_set_array,
  [sym_get_array] = sym_get_array,
  [sym_array_size] = sym_array_size,
  [sym_clear_array] = sym_clear_array,
  [sym_cat] = sym_cat,
  [sym_parameter] = sym_parameter,
  [sym_ref_parameter] = sym_ref_parameter,
  [sym_val_parameter] = sym_val_parameter,
  [sym_type] = sym_type,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_line_repeat1] = aux_sym_line_repeat1,
  [aux_sym_function_definition_repeat1] = aux_sym_function_definition_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_fun] = {
    .visible = true,
    .named = false,
  },
  [sym_function_close] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_return] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_while] = {
    .visible = true,
    .named = false,
  },
  [sym_end_block] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_PLUS_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_sizeof] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_free] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_cat] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_const] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_string] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_value] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_int] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_float] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_byte] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_iarray] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_farray] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_line] = {
    .visible = true,
    .named = true,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_function_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_function_return] = {
    .visible = true,
    .named = true,
  },
  [sym_if_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_while_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_unary_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym_set_array] = {
    .visible = true,
    .named = true,
  },
  [sym_get_array] = {
    .visible = true,
    .named = true,
  },
  [sym_array_size] = {
    .visible = true,
    .named = true,
  },
  [sym_clear_array] = {
    .visible = true,
    .named = true,
  },
  [sym_cat] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter] = {
    .visible = true,
    .named = true,
  },
  [sym_ref_parameter] = {
    .visible = true,
    .named = true,
  },
  [sym_val_parameter] = {
    .visible = true,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_line_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_function_definition_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_index = 1,
  field_lhs = 2,
  field_name = 3,
  field_rhs = 4,
  field_target = 5,
  field_type = 6,
  field_value = 7,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_index] = "index",
  [field_lhs] = "lhs",
  [field_name] = "name",
  [field_rhs] = "rhs",
  [field_target] = "target",
  [field_type] = "type",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
  [4] = {.index = 4, .length = 1},
  [5] = {.index = 5, .length = 2},
  [6] = {.index = 7, .length = 2},
  [7] = {.index = 9, .length = 2},
  [8] = {.index = 11, .length = 2},
  [9] = {.index = 13, .length = 3},
  [10] = {.index = 16, .length = 3},
  [11] = {.index = 19, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 1},
  [1] =
    {field_value, 1},
  [2] =
    {field_name, 1},
    {field_type, 2},
  [4] =
    {field_target, 1},
  [5] =
    {field_target, 0},
    {field_value, 2},
  [7] =
    {field_name, 2},
    {field_target, 0},
  [9] =
    {field_lhs, 1},
    {field_rhs, 3},
  [11] =
    {field_target, 1},
    {field_value, 3},
  [13] =
    {field_lhs, 2},
    {field_rhs, 4},
    {field_target, 0},
  [16] =
    {field_index, 2},
    {field_name, 0},
    {field_value, 4},
  [19] =
    {field_index, 4},
    {field_name, 0},
    {field_name, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(59);
      ADVANCE_MAP(
        '\n', 60,
        '!', 3,
        '#', 136,
        '%', 97,
        '&', 63,
        '*', 93,
        '+', 89,
        ',', 61,
        '-', 91,
        '/', 95,
        ':', 98,
        '<', 74,
        '=', 72,
        '>', 76,
        '@', 62,
        'b', 51,
        'c', 11,
        'e', 22,
        'f', 9,
        'i', 14,
        'r', 21,
        's', 27,
        'w', 25,
      );
      if (lookahead == '\t' ||
          lookahead == '\f' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(127);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '#', 136,
        '%', 4,
        '*', 5,
        '+', 6,
        '-', 7,
        '/', 8,
        ':', 98,
        '<', 2,
        '=', 72,
        's', 26,
      );
      if (lookahead == '\t' ||
          lookahead == '\f' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1);
      END_STATE();
    case 2:
      if (lookahead == '-') ADVANCE(99);
      END_STATE();
    case 3:
      if (lookahead == '=') ADVANCE(73);
      END_STATE();
    case 4:
      if (lookahead == '=') ADVANCE(87);
      END_STATE();
    case 5:
      if (lookahead == '=') ADVANCE(85);
      END_STATE();
    case 6:
      if (lookahead == '=') ADVANCE(83);
      END_STATE();
    case 7:
      if (lookahead == '=') ADVANCE(84);
      END_STATE();
    case 8:
      if (lookahead == '=') ADVANCE(86);
      END_STATE();
    case 9:
      if (lookahead == 'a') ADVANCE(39);
      if (lookahead == 'l') ADVANCE(35);
      if (lookahead == 'r') ADVANCE(20);
      if (lookahead == 'u') ADVANCE(32);
      END_STATE();
    case 10:
      if (lookahead == 'a') ADVANCE(52);
      END_STATE();
    case 11:
      if (lookahead == 'a') ADVANCE(44);
      if (lookahead == 'o') ADVANCE(31);
      END_STATE();
    case 12:
      if (lookahead == 'a') ADVANCE(53);
      END_STATE();
    case 13:
      if (lookahead == 'a') ADVANCE(48);
      END_STATE();
    case 14:
      if (lookahead == 'a') ADVANCE(42);
      if (lookahead == 'f') ADVANCE(70);
      if (lookahead == 'n') ADVANCE(45);
      END_STATE();
    case 15:
      if (lookahead == 'd') ADVANCE(81);
      END_STATE();
    case 16:
      if (lookahead == 'e') ADVANCE(133);
      END_STATE();
    case 17:
      if (lookahead == 'e') ADVANCE(101);
      END_STATE();
    case 18:
      if (lookahead == 'e') ADVANCE(79);
      END_STATE();
    case 19:
      if (lookahead == 'e') ADVANCE(36);
      END_STATE();
    case 20:
      if (lookahead == 'e') ADVANCE(17);
      END_STATE();
    case 21:
      if (lookahead == 'e') ADVANCE(46);
      END_STATE();
    case 22:
      if (lookahead == 'f') ADVANCE(66);
      if (lookahead == 'n') ADVANCE(15);
      END_STATE();
    case 23:
      if (lookahead == 'f') ADVANCE(100);
      END_STATE();
    case 24:
      if (lookahead == 'g') ADVANCE(106);
      END_STATE();
    case 25:
      if (lookahead == 'h') ADVANCE(28);
      END_STATE();
    case 26:
      if (lookahead == 'i') ADVANCE(54);
      END_STATE();
    case 27:
      if (lookahead == 'i') ADVANCE(54);
      if (lookahead == 't') ADVANCE(37);
      END_STATE();
    case 28:
      if (lookahead == 'i') ADVANCE(30);
      END_STATE();
    case 29:
      if (lookahead == 'i') ADVANCE(33);
      END_STATE();
    case 30:
      if (lookahead == 'l') ADVANCE(18);
      END_STATE();
    case 31:
      if (lookahead == 'n') ADVANCE(43);
      END_STATE();
    case 32:
      if (lookahead == 'n') ADVANCE(64);
      END_STATE();
    case 33:
      if (lookahead == 'n') ADVANCE(24);
      END_STATE();
    case 34:
      if (lookahead == 'n') ADVANCE(68);
      END_STATE();
    case 35:
      if (lookahead == 'o') ADVANCE(13);
      END_STATE();
    case 36:
      if (lookahead == 'o') ADVANCE(23);
      END_STATE();
    case 37:
      if (lookahead == 'r') ADVANCE(29);
      END_STATE();
    case 38:
      if (lookahead == 'r') ADVANCE(10);
      END_STATE();
    case 39:
      if (lookahead == 'r') ADVANCE(38);
      END_STATE();
    case 40:
      if (lookahead == 'r') ADVANCE(12);
      END_STATE();
    case 41:
      if (lookahead == 'r') ADVANCE(34);
      END_STATE();
    case 42:
      if (lookahead == 'r') ADVANCE(40);
      END_STATE();
    case 43:
      if (lookahead == 's') ADVANCE(47);
      END_STATE();
    case 44:
      if (lookahead == 't') ADVANCE(103);
      END_STATE();
    case 45:
      if (lookahead == 't') ADVANCE(131);
      END_STATE();
    case 46:
      if (lookahead == 't') ADVANCE(50);
      END_STATE();
    case 47:
      if (lookahead == 't') ADVANCE(105);
      END_STATE();
    case 48:
      if (lookahead == 't') ADVANCE(132);
      END_STATE();
    case 49:
      if (lookahead == 't') ADVANCE(16);
      END_STATE();
    case 50:
      if (lookahead == 'u') ADVANCE(41);
      END_STATE();
    case 51:
      if (lookahead == 'y') ADVANCE(49);
      END_STATE();
    case 52:
      if (lookahead == 'y') ADVANCE(135);
      END_STATE();
    case 53:
      if (lookahead == 'y') ADVANCE(134);
      END_STATE();
    case 54:
      if (lookahead == 'z') ADVANCE(19);
      END_STATE();
    case 55:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(128);
      END_STATE();
    case 56:
      if (eof) ADVANCE(59);
      ADVANCE_MAP(
        '\n', 60,
        '!', 3,
        '#', 136,
        '%', 96,
        '&', 63,
        '*', 92,
        '+', 88,
        ',', 61,
        '-', 90,
        '/', 94,
        '<', 75,
        '=', 72,
        '>', 76,
        '@', 62,
        'c', 107,
        'e', 113,
        'f', 120,
        'i', 114,
        'r', 111,
        'w', 115,
      );
      if (lookahead == '\t' ||
          lookahead == '\f' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(56);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 57:
      if (eof) ADVANCE(59);
      if (lookahead == '\n') ADVANCE(60);
      if (lookahead == '#') ADVANCE(136);
      if (lookahead == ',') ADVANCE(61);
      if (lookahead == '\t' ||
          lookahead == '\f' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(57);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(127);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 58:
      if (eof) ADVANCE(59);
      if (lookahead == '\n') ADVANCE(60);
      if (lookahead == '#') ADVANCE(136);
      if (lookahead == ',') ADVANCE(61);
      if (lookahead == '\t' ||
          lookahead == '\f' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(129);
      if (lookahead != 0) ADVANCE(130);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_AMP);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_fun);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_fun);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_function_close);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_function_close);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_return);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_return);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_if);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '-') ADVANCE(99);
      if (lookahead == '=') ADVANCE(77);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(77);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(78);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_while);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_while);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_end_block);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_end_block);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_PLUS_EQ);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_DASH_EQ);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(anon_sym_STAR_EQ);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(anon_sym_SLASH_EQ);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(anon_sym_PERCENT_EQ);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(anon_sym_PLUS);
      if (lookahead == '=') ADVANCE(83);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead == '=') ADVANCE(84);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(anon_sym_STAR);
      if (lookahead == '=') ADVANCE(85);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '=') ADVANCE(86);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      if (lookahead == '=') ADVANCE(87);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(anon_sym_LT_DASH);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(anon_sym_sizeof);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(anon_sym_free);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(anon_sym_free);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(anon_sym_cat);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(anon_sym_cat);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(anon_sym_const);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(anon_sym_string);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(122);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'd') ADVANCE(82);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(102);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(80);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(123);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(109);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'f') ADVANCE(67);
      if (lookahead == 'n') ADVANCE(108);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'f') ADVANCE(71);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'h') ADVANCE(116);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(117);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(110);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(65);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(69);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(112);
      if (lookahead == 'u') ADVANCE(118);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(119);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(104);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(124);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(121);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(sym_value);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(sym_value);
      if (lookahead == '.') ADVANCE(55);
      if (lookahead == 'b' ||
          lookahead == 'f') ADVANCE(126);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(127);
      END_STATE();
    case 128:
      ACCEPT_TOKEN(sym_value);
      if (lookahead == 'f') ADVANCE(126);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(128);
      END_STATE();
    case 129:
      ACCEPT_TOKEN(sym_string);
      if (lookahead == '\t' ||
          lookahead == '\f' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(129);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '#' &&
          lookahead != ',') ADVANCE(130);
      END_STATE();
    case 130:
      ACCEPT_TOKEN(sym_string);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '#' &&
          lookahead != ',') ADVANCE(130);
      END_STATE();
    case 131:
      ACCEPT_TOKEN(anon_sym_int);
      END_STATE();
    case 132:
      ACCEPT_TOKEN(anon_sym_float);
      END_STATE();
    case 133:
      ACCEPT_TOKEN(anon_sym_byte);
      END_STATE();
    case 134:
      ACCEPT_TOKEN(anon_sym_iarray);
      END_STATE();
    case 135:
      ACCEPT_TOKEN(anon_sym_farray);
      END_STATE();
    case 136:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(136);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 56},
  [2] = {.lex_state = 56},
  [3] = {.lex_state = 56},
  [4] = {.lex_state = 56},
  [5] = {.lex_state = 56},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 56},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 56},
  [15] = {.lex_state = 56},
  [16] = {.lex_state = 57},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 58},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 57},
  [41] = {.lex_state = 57},
  [42] = {.lex_state = 57},
  [43] = {.lex_state = 57},
  [44] = {.lex_state = 57},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 57},
  [47] = {.lex_state = 57},
  [48] = {.lex_state = 57},
  [49] = {.lex_state = 57},
  [50] = {.lex_state = 57},
  [51] = {.lex_state = 57},
  [52] = {.lex_state = 57},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 1},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 57},
  [57] = {.lex_state = 57},
  [58] = {.lex_state = 57},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 57},
  [61] = {.lex_state = 57},
  [62] = {.lex_state = 57},
  [63] = {.lex_state = 57},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LF] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_AMP] = ACTIONS(1),
    [anon_sym_fun] = ACTIONS(1),
    [sym_function_close] = ACTIONS(1),
    [anon_sym_return] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_while] = ACTIONS(1),
    [sym_end_block] = ACTIONS(1),
    [anon_sym_PLUS_EQ] = ACTIONS(1),
    [anon_sym_DASH_EQ] = ACTIONS(1),
    [anon_sym_STAR_EQ] = ACTIONS(1),
    [anon_sym_SLASH_EQ] = ACTIONS(1),
    [anon_sym_PERCENT_EQ] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_LT_DASH] = ACTIONS(1),
    [anon_sym_sizeof] = ACTIONS(1),
    [anon_sym_free] = ACTIONS(1),
    [anon_sym_cat] = ACTIONS(1),
    [anon_sym_const] = ACTIONS(1),
    [anon_sym_string] = ACTIONS(1),
    [sym_value] = ACTIONS(1),
    [anon_sym_int] = ACTIONS(1),
    [anon_sym_float] = ACTIONS(1),
    [anon_sym_byte] = ACTIONS(1),
    [anon_sym_iarray] = ACTIONS(1),
    [anon_sym_farray] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(53),
    [sym_line] = STATE(38),
    [sym_statement] = STATE(21),
    [sym_variable_definition] = STATE(27),
    [sym_function_definition] = STATE(27),
    [sym_function_return] = STATE(27),
    [sym_if_statement] = STATE(27),
    [sym_while_statement] = STATE(27),
    [sym_unary_assignment] = STATE(27),
    [sym_binary_assignment] = STATE(27),
    [sym_set_array] = STATE(27),
    [sym_get_array] = STATE(27),
    [sym_array_size] = STATE(27),
    [sym_clear_array] = STATE(27),
    [sym_cat] = STATE(27),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_LF] = ACTIONS(7),
    [anon_sym_AT] = ACTIONS(9),
    [anon_sym_AMP] = ACTIONS(9),
    [anon_sym_fun] = ACTIONS(11),
    [sym_function_close] = ACTIONS(13),
    [anon_sym_return] = ACTIONS(15),
    [anon_sym_if] = ACTIONS(17),
    [anon_sym_while] = ACTIONS(19),
    [sym_end_block] = ACTIONS(13),
    [anon_sym_free] = ACTIONS(21),
    [anon_sym_cat] = ACTIONS(23),
    [sym_identifier] = ACTIONS(25),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 16,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_fun,
    ACTIONS(15), 1,
      anon_sym_return,
    ACTIONS(17), 1,
      anon_sym_if,
    ACTIONS(19), 1,
      anon_sym_while,
    ACTIONS(21), 1,
      anon_sym_free,
    ACTIONS(23), 1,
      anon_sym_cat,
    ACTIONS(25), 1,
      sym_identifier,
    ACTIONS(27), 1,
      ts_builtin_sym_end,
    ACTIONS(29), 1,
      anon_sym_LF,
    STATE(3), 1,
      aux_sym_source_file_repeat1,
    STATE(21), 1,
      sym_statement,
    STATE(39), 1,
      sym_line,
    ACTIONS(9), 2,
      anon_sym_AT,
      anon_sym_AMP,
    ACTIONS(13), 2,
      sym_function_close,
      sym_end_block,
    STATE(27), 12,
      sym_variable_definition,
      sym_function_definition,
      sym_function_return,
      sym_if_statement,
      sym_while_statement,
      sym_unary_assignment,
      sym_binary_assignment,
      sym_set_array,
      sym_get_array,
      sym_array_size,
      sym_clear_array,
      sym_cat,
  [62] = 16,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(31), 1,
      ts_builtin_sym_end,
    ACTIONS(33), 1,
      anon_sym_LF,
    ACTIONS(39), 1,
      anon_sym_fun,
    ACTIONS(45), 1,
      anon_sym_return,
    ACTIONS(48), 1,
      anon_sym_if,
    ACTIONS(51), 1,
      anon_sym_while,
    ACTIONS(54), 1,
      anon_sym_free,
    ACTIONS(57), 1,
      anon_sym_cat,
    ACTIONS(60), 1,
      sym_identifier,
    STATE(3), 1,
      aux_sym_source_file_repeat1,
    STATE(21), 1,
      sym_statement,
    STATE(59), 1,
      sym_line,
    ACTIONS(36), 2,
      anon_sym_AT,
      anon_sym_AMP,
    ACTIONS(42), 2,
      sym_function_close,
      sym_end_block,
    STATE(27), 12,
      sym_variable_definition,
      sym_function_definition,
      sym_function_return,
      sym_if_statement,
      sym_while_statement,
      sym_unary_assignment,
      sym_binary_assignment,
      sym_set_array,
      sym_get_array,
      sym_array_size,
      sym_clear_array,
      sym_cat,
  [124] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_fun,
    ACTIONS(15), 1,
      anon_sym_return,
    ACTIONS(17), 1,
      anon_sym_if,
    ACTIONS(19), 1,
      anon_sym_while,
    ACTIONS(21), 1,
      anon_sym_free,
    ACTIONS(23), 1,
      anon_sym_cat,
    ACTIONS(25), 1,
      sym_identifier,
    STATE(32), 1,
      sym_statement,
    ACTIONS(9), 2,
      anon_sym_AT,
      anon_sym_AMP,
    ACTIONS(13), 2,
      sym_function_close,
      sym_end_block,
    STATE(27), 12,
      sym_variable_definition,
      sym_function_definition,
      sym_function_return,
      sym_if_statement,
      sym_while_statement,
      sym_unary_assignment,
      sym_binary_assignment,
      sym_set_array,
      sym_get_array,
      sym_array_size,
      sym_clear_array,
      sym_cat,
  [174] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(31), 4,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_AT,
      anon_sym_AMP,
    ACTIONS(63), 9,
      anon_sym_fun,
      sym_function_close,
      anon_sym_return,
      anon_sym_if,
      anon_sym_while,
      sym_end_block,
      anon_sym_free,
      anon_sym_cat,
      sym_identifier,
  [195] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(65), 1,
      anon_sym_EQ,
    ACTIONS(69), 1,
      anon_sym_COLON,
    ACTIONS(71), 1,
      anon_sym_LT_DASH,
    ACTIONS(73), 1,
      anon_sym_sizeof,
    ACTIONS(67), 5,
      anon_sym_PLUS_EQ,
      anon_sym_DASH_EQ,
      anon_sym_STAR_EQ,
      anon_sym_SLASH_EQ,
      anon_sym_PERCENT_EQ,
  [218] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(77), 1,
      anon_sym_AT,
    ACTIONS(79), 1,
      anon_sym_AMP,
    STATE(9), 2,
      sym_parameter,
      aux_sym_function_definition_repeat1,
    STATE(19), 2,
      sym_ref_parameter,
      sym_val_parameter,
    ACTIONS(75), 3,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_COMMA,
  [241] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(83), 1,
      anon_sym_AT,
    ACTIONS(86), 1,
      anon_sym_AMP,
    STATE(8), 2,
      sym_parameter,
      aux_sym_function_definition_repeat1,
    STATE(19), 2,
      sym_ref_parameter,
      sym_val_parameter,
    ACTIONS(81), 3,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_COMMA,
  [264] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(77), 1,
      anon_sym_AT,
    ACTIONS(79), 1,
      anon_sym_AMP,
    STATE(8), 2,
      sym_parameter,
      aux_sym_function_definition_repeat1,
    STATE(19), 2,
      sym_ref_parameter,
      sym_val_parameter,
    ACTIONS(89), 3,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_COMMA,
  [287] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(91), 3,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_COMMA,
    ACTIONS(93), 5,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
  [303] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(28), 1,
      sym_type,
    ACTIONS(95), 6,
      anon_sym_string,
      anon_sym_int,
      anon_sym_float,
      anon_sym_byte,
      anon_sym_iarray,
      anon_sym_farray,
  [318] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(20), 1,
      sym_type,
    ACTIONS(95), 6,
      anon_sym_string,
      anon_sym_int,
      anon_sym_float,
      anon_sym_byte,
      anon_sym_iarray,
      anon_sym_farray,
  [333] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(18), 1,
      sym_type,
    ACTIONS(95), 6,
      anon_sym_string,
      anon_sym_int,
      anon_sym_float,
      anon_sym_byte,
      anon_sym_iarray,
      anon_sym_farray,
  [348] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(99), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(97), 4,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [362] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(103), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(101), 4,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [376] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(107), 2,
      sym_identifier,
      sym_value,
    ACTIONS(105), 3,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_COMMA,
  [389] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(109), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_COMMA,
      anon_sym_AT,
      anon_sym_AMP,
  [400] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(111), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_COMMA,
      anon_sym_AT,
      anon_sym_AMP,
  [411] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(113), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_COMMA,
      anon_sym_AT,
      anon_sym_AMP,
  [422] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_COMMA,
      anon_sym_AT,
      anon_sym_AMP,
  [433] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(119), 1,
      anon_sym_COMMA,
    STATE(22), 1,
      aux_sym_line_repeat1,
    ACTIONS(117), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [447] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(119), 1,
      anon_sym_COMMA,
    STATE(23), 1,
      aux_sym_line_repeat1,
    ACTIONS(121), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [461] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 1,
      anon_sym_COMMA,
    STATE(23), 1,
      aux_sym_line_repeat1,
    ACTIONS(123), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [475] = 4,
    ACTIONS(128), 1,
      ts_builtin_sym_end,
    ACTIONS(132), 1,
      sym_string,
    ACTIONS(134), 1,
      sym_comment,
    ACTIONS(130), 2,
      anon_sym_LF,
      anon_sym_COMMA,
  [489] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(136), 3,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_COMMA,
  [498] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(138), 3,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_COMMA,
  [507] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(140), 3,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_COMMA,
  [516] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(142), 3,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_COMMA,
  [525] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(144), 3,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_COMMA,
  [534] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(91), 3,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_COMMA,
  [543] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(146), 3,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_COMMA,
  [552] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(123), 3,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_COMMA,
  [561] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(148), 3,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_COMMA,
  [570] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(150), 3,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_COMMA,
  [579] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(152), 3,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_COMMA,
  [588] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(154), 3,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_COMMA,
  [597] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(156), 3,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_COMMA,
  [606] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(27), 1,
      ts_builtin_sym_end,
    ACTIONS(158), 1,
      anon_sym_LF,
  [616] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(158), 1,
      anon_sym_LF,
    ACTIONS(160), 1,
      ts_builtin_sym_end,
  [626] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(162), 2,
      sym_identifier,
      sym_value,
  [634] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(164), 2,
      sym_identifier,
      sym_value,
  [642] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(166), 2,
      sym_identifier,
      sym_value,
  [650] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(168), 2,
      sym_identifier,
      sym_value,
  [658] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(170), 2,
      sym_identifier,
      sym_value,
  [666] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(172), 1,
      anon_sym_const,
    ACTIONS(174), 1,
      anon_sym_string,
  [676] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(176), 2,
      sym_identifier,
      sym_value,
  [684] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(178), 2,
      sym_identifier,
      sym_value,
  [692] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(180), 2,
      sym_identifier,
      sym_value,
  [700] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(182), 2,
      sym_identifier,
      sym_value,
  [708] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(184), 2,
      sym_identifier,
      sym_value,
  [716] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(186), 1,
      sym_identifier,
  [723] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(188), 1,
      sym_identifier,
  [730] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(190), 1,
      ts_builtin_sym_end,
  [737] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(192), 1,
      anon_sym_LT_DASH,
  [744] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(194), 1,
      anon_sym_COLON,
  [751] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(196), 1,
      sym_identifier,
  [758] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(198), 1,
      sym_identifier,
  [765] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(200), 1,
      sym_identifier,
  [772] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(158), 1,
      anon_sym_LF,
  [779] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(202), 1,
      sym_identifier,
  [786] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(132), 1,
      sym_identifier,
  [793] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(204), 1,
      sym_identifier,
  [800] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(206), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 62,
  [SMALL_STATE(4)] = 124,
  [SMALL_STATE(5)] = 174,
  [SMALL_STATE(6)] = 195,
  [SMALL_STATE(7)] = 218,
  [SMALL_STATE(8)] = 241,
  [SMALL_STATE(9)] = 264,
  [SMALL_STATE(10)] = 287,
  [SMALL_STATE(11)] = 303,
  [SMALL_STATE(12)] = 318,
  [SMALL_STATE(13)] = 333,
  [SMALL_STATE(14)] = 348,
  [SMALL_STATE(15)] = 362,
  [SMALL_STATE(16)] = 376,
  [SMALL_STATE(17)] = 389,
  [SMALL_STATE(18)] = 400,
  [SMALL_STATE(19)] = 411,
  [SMALL_STATE(20)] = 422,
  [SMALL_STATE(21)] = 433,
  [SMALL_STATE(22)] = 447,
  [SMALL_STATE(23)] = 461,
  [SMALL_STATE(24)] = 475,
  [SMALL_STATE(25)] = 489,
  [SMALL_STATE(26)] = 498,
  [SMALL_STATE(27)] = 507,
  [SMALL_STATE(28)] = 516,
  [SMALL_STATE(29)] = 525,
  [SMALL_STATE(30)] = 534,
  [SMALL_STATE(31)] = 543,
  [SMALL_STATE(32)] = 552,
  [SMALL_STATE(33)] = 561,
  [SMALL_STATE(34)] = 570,
  [SMALL_STATE(35)] = 579,
  [SMALL_STATE(36)] = 588,
  [SMALL_STATE(37)] = 597,
  [SMALL_STATE(38)] = 606,
  [SMALL_STATE(39)] = 616,
  [SMALL_STATE(40)] = 626,
  [SMALL_STATE(41)] = 634,
  [SMALL_STATE(42)] = 642,
  [SMALL_STATE(43)] = 650,
  [SMALL_STATE(44)] = 658,
  [SMALL_STATE(45)] = 666,
  [SMALL_STATE(46)] = 676,
  [SMALL_STATE(47)] = 684,
  [SMALL_STATE(48)] = 692,
  [SMALL_STATE(49)] = 700,
  [SMALL_STATE(50)] = 708,
  [SMALL_STATE(51)] = 716,
  [SMALL_STATE(52)] = 723,
  [SMALL_STATE(53)] = 730,
  [SMALL_STATE(54)] = 737,
  [SMALL_STATE(55)] = 744,
  [SMALL_STATE(56)] = 751,
  [SMALL_STATE(57)] = 758,
  [SMALL_STATE(58)] = 765,
  [SMALL_STATE(59)] = 772,
  [SMALL_STATE(60)] = 779,
  [SMALL_STATE(61)] = 786,
  [SMALL_STATE(62)] = 793,
  [SMALL_STATE(63)] = 800,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [36] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(60),
  [39] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(52),
  [42] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [45] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [48] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(40),
  [51] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [54] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(51),
  [57] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(58),
  [60] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [63] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 2, 0, 1),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_definition_repeat1, 2, 0, 0),
  [83] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_definition_repeat1, 2, 0, 0), SHIFT_REPEAT(56),
  [86] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_definition_repeat1, 2, 0, 0), SHIFT_REPEAT(57),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 3, 0, 1),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unary_assignment, 3, 0, 5),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [99] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [103] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_return, 1, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 1, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ref_parameter, 3, 0, 3),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter, 1, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_val_parameter, 3, 0, 3),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line, 1, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line, 2, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_line_repeat1, 2, 0, 0),
  [125] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_line_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cat, 3, 0, 4),
  [130] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cat, 3, 0, 4),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [134] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_get_array, 5, 0, 11),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_set_array, 5, 0, 10),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 1, 0, 0),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_definition, 3, 0, 3),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_return, 2, 0, 2),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_size, 3, 0, 6),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_clear_array, 2, 0, 1),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_while_statement, 4, 0, 7),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cat, 4, 0, 8),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 4, 0, 7),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_assignment, 5, 0, 9),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [190] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_keszeg(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "keszeg",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 1,
      .minor_version = 0,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
